language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
install:
  - npm install
  - npm install typescript
  - npm install tslint
  - ./node_modules/.bin/tsc -v
  - ./node_modules/.bin/tslint -v
  - tslint -e "node_modules/**/*" "**/*.ts"
  - ./node_modules/.bin/tsc -p .